src/MvcCore.Site/Areas/Produtos/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcCore.Site.Extensions;

namespace MvcCore.Site.Areas.Produtos.Controllers
{
    [Area("Produtos")]
    [Authorize]
    public class CadastroController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Policy = "PodeAdicionar")]
        public IActionResult Inserir()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Gestor")]
        public IActionResult SecretRole()
        {
            return View();
        }

        [Authorize(Policy = "PodeEditar")]
        public IActionResult SecretClaim()
        {
            return View("SecretRole");
        }

        [Authorize(Policy = "PodeExcluir")]
        public IActionResult SecretClaimValue()
        {
            return View("SecretRole");
        }

        [ClaimsAuthorize("Produtos","PodeLer")]
        public IActionResult CustomSecretClaimValue()
        {
            return View("SecretRole");
        }
    }
}

src/MvcCore.Site/Controllers/CrudController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCore.Site.Data;
using MvcCore.Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCore.Site.Controllers
{
    public class CrudController : Controller
    {
        private readonly CustomDbContext _context;

        public CrudController(CustomDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // Conceitos de CRUD usando o Entity Framework

            // Create
            var aluno = new Aluno
            {
                Nome = "Tiago",
                DataNascimento = DateTime.Now,
                Email = "tiago@gmail.com"
            };

            _context.Alunos.Add(aluno); // Salvando em memória
            _context.SaveChanges();     // Realizando operação no Banco de Dados

            // Read
            var aluno2 = _context.Alunos.Find(aluno.Id); 
            var aluno3 = _context.Alunos.FirstOrDefault(x => x.Email == aluno.Email); // Recuperando com base em uma propriedade da classe

            // Update
            aluno.Nome = "Tiago Pala";
            _context.Alunos.Update(aluno);
            _context.SaveChanges();

            // Delete
            _context.Alunos.Remove(aluno);
            _context.SaveChanges();

            return View();
        }
    }
}

src/MvcCore.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - MvcCore.Site</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site_bundle.min.css"/>
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetMvcCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crud" asp-action="Index">Crud</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="Inserir">Inserir</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="SecretRole">Secret</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="SecretClaim">SecretClaim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="SecretClaimValue">SecretClaimValue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="CustomSecretClaimValue">CustomSecret</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Rodapé - <email email-domain="gmail.com">contato</email> - <email>suporte</email>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/js/site_bundle.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>